spring:
  #database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gd
    username: root
    password: admin

  #jap
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hiberbate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
server:
  tomcat:
    connection-timeout: 60s
  port: 8443


